### ISSUE TITLE
multiple-field-delimiter & multiple-value-delimiter

### ISSUE THREAD

**Issue by gregordonsky** [techdivision/import-attribute#41]
Multiple Field Delimiter and Multiple Value Delimiter are valid configuration params, but it is undocumented.

Also the lines:

https://github.com/techdivision/import-attribute/blob/fa31f594c518c19e7eb41a34202120ec7750a934/src/Observers/AttributeOptionExportObserver.php#L61-L62

https://github.com/techdivision/import-attribute/blob/fa31f594c518c19e7eb41a34202120ec7750a934/src/Observers/AttributeOptionValueExportObserver.php#L64

Does not use Multiple Field Delimiter value if set in configuration.
I use this fix:

```php
$attributeOptionValues = $this->explode($this->getValue(ColumnKeys::ATTRIBUTE_OPTION_VALUES), $this->getMultipleFieldDelimiter());
$attributeOptionSortOrder = $this->explode($this->getValue(ColumnKeys::ATTRIBUTE_OPTION_SORT_ORDER), $this->getMultipleFieldDelimiter());
```

```php
$attributeOptionValues = $this->explode($this->getValue(ColumnKeys::ATTRIBUTE_OPTION_VALUES), $this->getMultipleFieldDelimiter());
```

**Comment by wagnert** [comment]
@gregordonsky Hey, thanks for reporting. You're right, i'll refactor this with the next version. Optionally it'll be nice, when you'll send me a PR so i can merge the changes. Would this be possible? :-)

**Comment by gregordonsky** [comment]
I hope the PR is right, first time on github :-)
