### ISSUE TITLE
Attribute Option Value failes

### ISSUE THREAD

**Issue by pcs-matze** [techdivision/import-attribute#49]
Hi there,

I've a strange behavior and it seems like a bug in attribute option values.
I've a attribute.csv and just for one attribute I've set option values in default store view code and for the same attribute in one specific store view code. 
In class TechDivision\Import\Attribute\Observers\AttributeOptionValueExportObserver the method $this->getLastEntityId() always returns the last entity id of previous processed attribute, but not the entity id of the current attribute for the values should be imported. 
Example: I've attribute A, B, C, all attributes in default store code and in a specific store code (so 6 lines in CSV), just attribute B has option values, alll other are empty. But in echDivision\Import\Attribute\Observers\AttributeOptionValueExportObserver the function getLastEntityId() returns just the id of attribute C, but there is no entry in "ExportableTrait->getArtefactsByTypeAndEntityId" and an error will be thrown. If the execution order is A, C, B, so the attribute with the option values is the last one in csv, then it will work.

CSV:
`store_view_code,attribute_set_name,attribute_group_name,entity_type_code,attribute_code,sort_order,data_type,frontend_label,backend_type,frontend_input,source_model,is_filterable,backend_model,attribute_option_values
,Default,TradeControl,catalog_product,einband,10,select,Einband,int,select,,1,,
,Default,TradeControl,catalog_product,farbe,10,select,"Farbe (ISO)",int,select,,1,,
,Default,TradeControl,catalog_product,garantie_monate,10,int,garantie_monate,int,text,,0,,
,Default,TradeControl,catalog_product,gewicht_kg,1,select,"Gewicht kg",int,select,,1,,
,Default,TradeControl,catalog_product,groesse_xxs_xxl_system,10,select,Größe,int,select,,1,,
,Default,TradeControl,catalog_product,inet,10,select,INet,int,select,,1,,
,Default,TradeControl,catalog_product,jahrgang,10,select,Jahrgang,int,select,,1,,
,Default,TradeControl,catalog_product,laender,2,multiselect,Länder,varchar,multiselect,,1,Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend,
,Default,TradeControl,catalog_product,machcode,10,select,Matchcode,int,select,,1,,
,Default,TradeControl,catalog_product,material,1,multiselect,material,varchar,multiselect,,1,Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend,
,Default,TradeControl,catalog_product,rebsorte,10,select,Rebsorte,int,select,,1,,
,Default,TradeControl,catalog_product,sonstiges,10,multiselect,sonstiges,varchar,multiselect,,1,Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend,
,Default,TradeControl,catalog_product,sprachen,2,multiselect,Sprachen,varchar,multiselect,,1,Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend,"Sprache1,Sprache2,Sprache3"
,Default,TradeControl,catalog_product,tags,9999,text,Tags,text,textarea,,0,,
en,Default,TradeControl,catalog_product,einband,10,select,Cover,int,select,,1,,
en,Default,TradeControl,catalog_product,farbe,10,select,"color (iso)",int,select,,1,,
en,Default,TradeControl,catalog_product,garantie_monate,10,int,"warranty (month)",int,text,,0,,
en,Default,TradeControl,catalog_product,gewicht_kg,1,select,"weight (kg)",int,select,,1,,
en,Default,TradeControl,catalog_product,groesse_xxs_xxl_system,10,select,size,int,select,,1,,
en,Default,TradeControl,catalog_product,inet,10,select,inet,int,select,,1,,
en,Default,TradeControl,catalog_product,jahrgang,10,select,vintage,int,select,,1,,
en,Default,TradeControl,catalog_product,laender,2,multiselect,Countries,varchar,multiselect,,1,Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend,
en,Default,TradeControl,catalog_product,machcode,10,select,machcode,int,select,,1,,
en,Default,TradeControl,catalog_product,material,1,multiselect,material,varchar,multiselect,,1,Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend,
en,Default,TradeControl,catalog_product,sonstiges,10,multiselect,sonstiges,varchar,multiselect,,1,Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend,
en,Default,TradeControl,catalog_product,sprachen,2,multiselect,Languages,varchar,multiselect,,1,Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend,"Sprache1-en,Sprache2-en,Sprache3-en"
en,Default,TradeControl,catalog_product,tags,9999,text,Tags,text,textarea,,0,,
en,Default,TradeControl,catalog_product,rebsorte,10,select,"Grape variety",int,select,,1,,`

**Comment by wagnert** [comment]
@pcs-matze Thanks for reporting. I'll check this soon and come back to you.

**Comment by wagnert** [comment]
@pcs-matze You're file has the wrong structure. We have an example [file](https://github.com/techdivision/import-sample-data/blob/4.x/generic/data/attributes/multi-storeview/attribute-import_20170428-124902_01.csv) to give you an idea of how it has to look like. Additionally, I've re-structured and append your file [here ](https://github.com/techdivision/import-attribute/files/4627705/attribute-import_20200514-123114_01.zip) :-) Keep me updated if this solves your problems.

**Comment by pcs-matze** [comment]
Thanks for your assistance, your hint works!
It seems just the order of the datasets were wrong.

**Comment by wagnert** [comment]
Perfect, it's awesome that we can help you :)
