### ISSUE TITLE
Add validator that backend_type is set

### ISSUE THREAD

**Issue by amenk** [techdivision/import-attribute#51]
I managed to import some attributes with backend_type = null, because in the importer I used before, varchar was assumed as default.

This causes such errors when searching in the admin panel in Catalog -> Products

     Column not found: 1054 Unknown column 'my_custom_attribute' in 'where clause' a

Do you think it would make sense to add a validation for backend_type to be set before importing?

(low prio, as the fix is to just set backend_type)

**Comment by wagnert** [comment]
Hi @amenk, in general, the validation is very basic at the moment, so I think it will make sense probably. I'll check that later on :)

**Comment by wagnert** [comment]
@adhocore Not really bypass, disable it by configuration. The next version will have the functionality to do nothing if no value has been specified in the CSV file. this should make things easier.

**Comment by wagnert** [comment]
We've added validation for `frontend_input` and `backend_type` with version 3.8.22.
