### ISSUE TITLE
When entity_type_code is not supplied, the validation for attribute_set_name etc. fails

### ISSUE THREAD

**Issue by amenk** [techdivision/import-attribute#52]
I was importing attributes for products, without specifying the entity_type_code

This was working fine, but when I added attribute_set_name and attribute_set_group it started failing:

	+---------------------------------+------+----------------------+---------------------------------------------------------------+
	| attribute-import_19700101_1.csv | 2    | attribute_set_name   | Found invalid value "Default" for column "attribute_set_name" |
	| attribute-import_19700101_1.csv | 3    | attribute_group_name | Found invalid attribute group name "PIM"                      |

This validation problem can be fixed by specifying entity_type_code, but this is misleading and needed debugging.

Either we should require entity_type_code, or consistently default it to catalog_products

**Comment by wagnert** [comment]
Hi @amenk, with version [3.8.24](https://github.com/techdivision/import-cli-simple/releases/tag/3.8.24) the error messages should be correct. The column `entity_type_code`, as well as `attribute_set_name` and `attribute_group_name` are mandatory on main row, but not on store view level.
