### ISSUE TITLE
Option Validation

### ISSUE THREAD

**Issue by TD-ellguthe** [techdivision/import-attribute#63]
[Here](https://github.com/techdivision/import-attribute/blob/fa623234a5c3d99253ba91e6f30328f4d4cb2a86/src/Observers/AttributeOptionValueExportObserver.php#L66) should happen a validation.

Example:
```
if (!isset($adminValueArtefacts[$key])) {
    // throw exception with message that points to faulty data in CSV file
}
```

**Comment by Mardl** [comment]
thx a lot.
https://github.com/techdivision/import-attribute/commit/37b755d35ef08a0610e061e1ca57dd1c9d983bef?diff=unified
